# Generated by Django 4.0.6 on 2022-08-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_discount_price'),
        ('accounts', '0002_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
