# Generated by Django 4.0.6 on 2022-08-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_cartitem_product_cartitem_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
