# Generated by Django 4.0.6 on 2022-08-20 09:52

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_featured'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('featured_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
